### ISSUE TITLE
Not compatible with Firefox 8

### ISSUE THREAD

**Issue by rampr** [thedarkone/firepicker#15]
Firepicker isn't compatible with firefox 8

**Comment by davidjohnstone** [comment]
I noticed that too. If you want to get Firepicker working right now, go into Firefox's extensions directory (which is something like `C:\Users\Me\AppData\Roaming\Mozilla\Firefox\Profiles\...\extensions` on Windows) open up `firepicker@thedarkone.xpi` (`xpi` files are just `zip` files in disguise) and edit `install.rdf` by changing `em:maxVersion` to 11.0 or some larger number than 8.0. Save that and start Firefox, and Firepicker should work fine again.

**Comment by rampr** [comment]
Thanks. That helped.

**Comment by tszynalski** [comment]
I couldn't get the above instructions to work (when I changed the rdf file, Firepicker was removed). But I found a simpler way:
1. Go to https://addons.mozilla.org/en-US/firefox/addon/firepicker/
2. Click "Add to Firefox".
3. Click "Install anyway".

You may have to uninstall it first.

**Comment by jensimmons** [comment]
Neither solution above is working for me (on Mac). Gosh I miss FirePicker a LOT. I use it constantly. Any idea of when an update can be pushed? Sounds like it works, it just needs a tweak.

**Comment by jensimmons** [comment]
I forked the github repo, bumped the version number to 8.9, pushed the code to my repo https://github.com/jensimmons/firepicker, and submitted a pull request to the real repo. Hopefully the official add-on will be updated soon. Meanwhile, you can grab a copy from my repo.

**Comment by rampr** [comment]
I'm on a mac and @davidjohnstone's instructions worked for me

**Comment by jensimmons** [comment]
I am on Lion (Mac OS X.7.2), and the files have moved around. It was tough to find where the addons are stored. They are all in here in various places:

Macintosh HD/Users/You/LibraryApplication Support/Firefox/Profiles/yourprofilesname/

Note that the Library folder is now hidden in Mac OS X.7, so you need to either use the command line or find a tool that will show you the file system with invisible files hidden (like a code editor, or an FTP program). 

The problem is the only file I see for firepicker is the .xpi file, and that's not editable. 

I did try the "Install anyway" option, and it wouldn't install. I'm sure things have changed, or may be different from OS to OS. 

My final solution was to download FireFox 7, and get back to work.

**Comment by csytan** [comment]
An easy way to run Firepicker with FF8 is to disable compatibility checking for extensions.

Here's a how-to video I found:
http://www.youtube.com/watch?v=4W7K64LJkQY

**Comment by jakecaputo** [comment]
Thanks man, I got it figured out though! 

--Thanks!
Jake Caputo
815.252.4698
jake@designcrumbs.com (mailto:jake@designcrumbs.com)
www.DesignCrumbs.com (http://www.DesignCrumbs.com)

**Comment by thedarkone** [comment]
This has been fixed.

**Comment by jensimmons** [comment]
Yay!! Oh, and now FF9 is out. Mozilla apparently is going to redo how the system checks for add-on compatibility to make this perpetual need to update the add-on version number go away... but that's in the future / hasn't been launched yet.

Does Firepicker work with FF9? FF10?

**Comment by jensimmons** [comment]
Oh, I should have looked more closely before commenting. Yes v 1.3.7 works will all versions of FF9. Excellent. AND a weird bug I'd been seeing is fixed. Thanks!!!!! This tool is truly something I used constantly.  Thanks for all of you work on it. :D
