### ISSUE TITLE
make firefox 4.0.* compatible

### ISSUE THREAD

**Issue by aadis** [thedarkone/firepicker#6]
firepicker is a very great extension, and one of my faves. Can you please make it 4.0\* compatible so I can continue using it with the upcoming release.

**Comment by aaronbushnell** [comment]
+1 for this.
I use Firepicker at least 5-6 times a day at work.  I can't make the switch without this.

**Comment by thedarkone** [comment]
Hah! It seems the plugin is already fully FF4 and Firebug 1.6 compatible!

All I had to do was to mark it "FF4 ready" ... if I only knew this was going to be _this easy_ :). You see the previous 3.0 -> 3.6 upgrade took something like 5 hours of horrible debugging, that's why I was very reluctant to start working on FF4 compatibility and was putting it off for as long as I could. Sorry about that guys ;).

I'm closing the issue, if you run into FF4 related problems, please open a new ticket.
